api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
    TokenRefreshView,
)
from rest_framework import routers

router = routers.DefaultRouter()
router.register('products', views.ProductViewSet, basename='product')
router.register('categories', views.CategoryViewSet, basename='category')
router.register('orders', views.OrderViewAPI, basename='order')



app_name = 'api'
urlpatterns = [
    path('register/', views.UserRegisterViewAPI.as_view(), name='register_api'),
    path('users/user-activation/email/<str:token>/', views.UserAccountActivationAPI.as_view(), name='activation_email_api'),
    path('users/user-activation/sms/', views.UserAccountActivationAPI.as_view(), name='activation_sms_api'),
    path('users/login/', views.LoginUserAPI.as_view(), name='login_api'),
    path('users/logout/', views.LogoutUserAPI.as_view(), name='logout_api'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('users/reset-password/', views.ResetPasswordAPI.as_view(), name='reset_password_api'),
]

urlpatterns += router.urls

core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/', include('api.urls', namespace='api')),
]

home/urls.py
from django.urls import path, include
from . import views


bucket_url = [
    path("", view=views.BucketListView.as_view(), name="bucket"),
    path(
        "delete_obj_bucket/<path:key>",
        view=views.DeleteObjectBucketView.as_view(),
        name="delete_obj_bucket",
    ),
    path(
        "download_obj_bucket/<path:key>",
        view=views.DownloadObjectBucketView.as_view(),
        name="download_obj_bucket",
    ),
]

app_name = "home"
urlpatterns = [
    path("", view=views.HomeView.as_view(), name="home"),
    path("categories/<slug:category_slug>", view=views.HomeView.as_view(), name="categories"),
    path("bucket/", include(bucket_url)),
    path(
        "products/<slug:slug>/",
        view=views.ProductDetail.as_view(),
        name="product_detail",
    ),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/create-order/', views.OrderCreateView.as_view(), name='order_create'),
    path('cart/detail/<int:order_id>', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/detail/remove/<int:order_id>', views.OrderDetailRemoveView.as_view(), name='order_remove'),
    path('pay/<int:order_id>', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderPayVerifyView.as_view(), name='order_verify'),
    path('coupon/<int:order_id>', views.CouponApplyView.as_view(), name='coupon_apply'),
]

home/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from home.managers import ProductManager
# from ckeditor.fields import RichTextField




class Category(models.Model):
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children', blank=True, null=True)
    is_child = models.BooleanField(default=False)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, blank=True, null=True)
    
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        #prevent a category to be itself parent
        if self.pk and self.parent and self.parent.pk == self.pk:
            self.parent = None
        self.slug = slugify(value=self.name)
        return super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("home:categories", kwargs={"category_slug": self.slug})


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, null=True)
    # description = RichTextField()
    description = models.TextField()
    slug = models.SlugField(blank=True, null=True)
    category = models.ManyToManyField(Category, related_name='products')
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    default_objects = models.Manager()
    objects = ProductManager()

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'
    
    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(value=self.name)
        return super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("home:product_detail", kwargs={"slug": self.slug})
    

home/forms.py
from django import forms


class UploadFileForm(forms.Form):
    upl_file = forms.FileField(label='File', widget=forms.FileInput(attrs={'class':'form-control'}))
    

home/views.py
import os
from django.conf import settings
from django.shortcuts import redirect, render
from django.views import View

from orders.forms import AddToCartForm
from .models import Product, Category
from django.contrib import messages
from . import tasks
from . import forms
from utils import IsAdminUserMixin



class HomeView(View):
    def get(self, request, category_slug=None):
        q = request.GET.get('q', '')
        if q:
            products = Product.objects.q_search(q)
        else:
            products = Product.objects.all()
        categories = Category.objects.all()
        if category_slug:
            category = categories.filter(slug=category_slug).first()
            products = products.filter(category=category)
        categories = categories.filter(is_child=False)
        return render(
            request, template_name="home/home.html", context={"products": products, 'categories':categories}
        )


class ProductDetail(View):
    def get(self, request, *args, **kwargs):
        product = Product.objects.filter(slug=kwargs.get("slug"))
        if product.exists():
            form = AddToCartForm()
            return render(request, "home/detail.html", {"product": product.first(), 'form':form})
        messages.error(request, message="product not found")
        return redirect("home:home")


class BucketListView(IsAdminUserMixin, View):
    form_class = forms.UploadFileForm

    def get(self, request):
        form = self.form_class()
        objects = tasks.get_bucket_list()
        return render(request, "home/bucket.html", {"objects": objects, "form": form})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES["upl_file"]
            # Save the file to a temporary location
            temp_file_path = os.path.join(settings.AWS_LOCAL_DIRECTORY, file.name)
            with open(temp_file_path, "wb+") as destination:
                for chunk in file.chunks():
                    destination.write(chunk)
            # Upload the file to S3
            result = tasks.upload_obj_bucket.delay(
                temp_file_path, object_name=file.name
            )
            result.wait()  # TODO: we can add loading or uploading page with ajax and make it async
            # Remove the temporary file
            os.remove(temp_file_path)
            messages.success(request, "uploaded!")
            return redirect("home:bucket")
        messages.error(request, "invalid files")
        return redirect("home:bucket")


class DeleteObjectBucketView(IsAdminUserMixin, View):
    def get(self, request, key):
        tasks.delete_obj_bucket.delay(key)
        messages.success(request, "object will delete soon...")
        return redirect("home:bucket")


class DownloadObjectBucketView(IsAdminUserMixin, View):
    def get(self, request, key):
        tasks.download_obj_bucket.delay(key)
        messages.success(request, "object will download soon...")
        return redirect("home:bucket")

home/templates/home/bucket.html
{% extends "shared/base.html" %}

{% block title %}Bucket list{% endblock title %}

{% block content %}
<div class="card border-0 shadow-lg p-1">
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Size</th>
            <th scope="col">Download</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
            {% for obj in objects %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ obj.Key }}</td>
                    <td>{{ obj.Size|filesizeformat }}</td>
                    <td><a href="{% url "home:delete_obj_bucket" obj.Key %}" class="link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Delete</a></td>
                    <td><a href="{% url "home:download_obj_bucket" obj.Key %}" class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Download</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>
        <input type="submit" value='Upload' class="btn btn-primary">
    </form>
</div>
{% endblock content %}

home/templates/home/detail.html
{% extends "shared/base.html" %}

{% block title %}Detail{% endblock title %}

{% block content %}
    <div class="card mb-3 border border-0 shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <img src="{{ product.image.url }}" class="card-img-top w-25">
        <br>
        <hr>
        <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
        <p class="card-text">{{ product.description }}</p>
        <p class="card-text">{{ product.price }}</p>
        <p class="card-text"><small class="text-body-secondary">Last updated : {{ product.updated }}</small></p>
        <p class="card-text"><small class="text-body-secondary">created : {{ product.created }}</small></p>
        </div>
        <br>
        <hr>
        <form action="{% url "orders:cart_add" product.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value='Add To Cart'>
        </form>
    </div>
{% endblock content %}

home/templates/home/home.html
{% extends "shared/base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}
    <a href="{% url "home:home" %}" class="btn btn-primary">all</a>
    {% for category in categories %}
        <div class="btn-group">
                <a type="button" class="btn btn-danger" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
                </button>
            <ul class="dropdown-menu">
                {% for child in category.children.all %}
                    <li><a class="dropdown-item" href="{{ child.get_absolute_url }}">{{ child.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
    <br>
    <hr>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for product in products %}
            <div class="col">
            <div class="card h-100 grid_item shadow-lg">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{{ product.image.url }}" class="card-img-top rounded-pill">
                </a>
                <hr>
                <div class="card-body">
                <p><a href="{{ product.get_absolute_url }}" class="link-body-emphasis link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover"><h5 class="card-title">{{ product.name }}</h5></a></p>
                <p class="card-text">{{ product.price }}</p>
                <p class="card-text">{{ product.description|truncatewords:10 }}</p>
                </div>
                <div class="card-footer">
                <small class="text-body-secondary">Last updated : {{ product.updated }}</small>
                </div>
            </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}