accounts/urls.py
from django.urls import path
from . import views



app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='user_register'),
    path('logout/', views.LogoutView.as_view(), name='user_logout'),
    path('login/', views.LoginView.as_view(), name='user_login'),
    path('user-verification/<str:token>/', views.UserVerificationView.as_view(), name='user_verification_token'),
    path('user-verification/', views.UserVerificationView.as_view(), name='user_verification'),
    path('user-profile/', views.UserProfileView.as_view(), name='user_profile'),
]

api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
    TokenRefreshView,
)
from rest_framework import routers

router = routers.DefaultRouter()
router.register('products', views.ProductViewSet, basename='product')
router.register('categories', views.CategoryViewSet, basename='category')
router.register('orders', views.OrderViewAPI, basename='order')



app_name = 'api'
urlpatterns = [
    path('register/', views.UserRegisterViewAPI.as_view(), name='register_api'),
    path('users/user-activation/email/<str:token>/', views.UserAccountActivationAPI.as_view(), name='activation_email_api'),
    path('users/user-activation/sms/', views.UserAccountActivationAPI.as_view(), name='activation_sms_api'),
    path('users/login/', views.LoginUserAPI.as_view(), name='login_api'),
    path('users/logout/', views.LogoutUserAPI.as_view(), name='logout_api'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('users/reset-password/', views.ResetPasswordAPI.as_view(), name='reset_password_api'),
]

urlpatterns += router.urls

core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/', include('api.urls', namespace='api')),
]

home/urls.py
from django.urls import path, include
from . import views


bucket_url = [
    path("", view=views.BucketListView.as_view(), name="bucket"),
    path(
        "delete_obj_bucket/<path:key>",
        view=views.DeleteObjectBucketView.as_view(),
        name="delete_obj_bucket",
    ),
    path(
        "download_obj_bucket/<path:key>",
        view=views.DownloadObjectBucketView.as_view(),
        name="download_obj_bucket",
    ),
]

app_name = "home"
urlpatterns = [
    path("", view=views.HomeView.as_view(), name="home"),
    path("categories/<slug:category_slug>", view=views.HomeView.as_view(), name="categories"),
    path("bucket/", include(bucket_url)),
    path(
        "products/<slug:slug>/",
        view=views.ProductDetail.as_view(),
        name="product_detail",
    ),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/create-order/', views.OrderCreateView.as_view(), name='order_create'),
    path('cart/detail/<int:order_id>', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/detail/remove/<int:order_id>', views.OrderDetailRemoveView.as_view(), name='order_remove'),
    path('pay/<int:order_id>', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderPayVerifyView.as_view(), name='order_verify'),
    path('coupon/<int:order_id>', views.CouponApplyView.as_view(), name='coupon_apply'),
]

templates/include/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-dark" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/include/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url "home:home" %}">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                    {% if request.user.is_admin %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/admin">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url "home:bucket" %}">Buckets</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url "accounts:user_logout" %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url "accounts:user_profile" %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url "orders:cart" %}">Orders({{ cart|length }})</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url "accounts:user_register" %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url "accounts:user_login" %}">Login</a>
                    </li>
                {% endif %}
            </ul>
            <form action="{% url "home:home" %}" method='get' class="d-flex" role="search">
                <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>